import{i as y,a as v,S as b}from"./assets/vendor-Dpd1z_xS.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))p(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&p(u)}).observe(document,{childList:!0,subtree:!0});function c(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function p(t){if(t.ep)return;t.ep=!0;const r=c(t);fetch(t.href,r)}})();const l=document.querySelector(".gallery"),h=e=>`
  <div class="photo-el">
  <a href="${e.largeImageURL}">
    <img class="mini-image" src="${e.webformatURL}" alt="${e.tags}">
  </a>
  <div class="photo-descr">
  <div class="descr-el"><h2 class="descr-header">Likes</h2><p class="descr-text">${e.likes}</p></div>
  <div class="descr-el"><h2 class="descr-header">Views</h2><p class="descr-text">${e.views}</p></div>
  <div class="descr-el"><h2 class="descr-header">Comments</h2><p class="descr-text">${e.comments}</p></div>
  <div class="descr-el"><h2 class="descr-header">Downloads</h2><p class="descr-text">${e.downloads}</p></div>
  </div>
  </div>`,a=document.querySelector(".loader"),o=document.querySelector(".load-button"),n=document.querySelector(".js-form");let d=1,m,i;const f=(e,s)=>v.get(`https://pixabay.com/api/?key=48328522-58f8fcf940ace01c2f71e55b2&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&page=${e}&per_page=15`),L=async()=>{try{d=1;const{data:e}=await f(d,i);if(a.style.display="none",e.totalHits===0){y.show({theme:"dark",icon:"icon-person",message:"Sorry, there are no images matching your search query. Please try again!",position:"center"}),n.reset(),l.innerHTML="",o.style.display="none";return}const s=e.hits.map(c=>h(c)).join("");l.innerHTML=s,m=new b(".gallery a",{captions:!0,captionsData:"alt",captionDelay:500}),o.style.display="block"}catch(e){a.style.display="none",console.log(e)}},w=async e=>{try{if(e.preventDefault(),a.style.display="block",i=n.elements.input.value.trim(),i===""){y.show({theme:"dark",icon:"icon-person",message:"Please enter data to search",position:"center"}),a.style.display="none",n.reset();return}await L(),o.addEventListener("click",g)}catch(s){console.log(s)}},g=async e=>{try{e.preventDefault(),a.style.display="block",o.style.display="none",d++,i=n.elements.input.value.trim();const{data:s}=await f(d,i),c=s.hits.map(r=>h(r)).join("");a.style.display="none",l.insertAdjacentHTML("beforeend",c),m.refresh();const t=l.querySelector(".photo-el").getBoundingClientRect().height;if(window.scrollBy({top:2*t,behavior:"smooth"}),s.hits<15){o.removeEventListener("click",g),y.show({theme:"dark",icon:"icon-person",message:"We're sorry, but you've reached the end of search results.",position:"center"});return}o.style.display="block"}catch(s){console.log(s)}};n.addEventListener("submit",w);
//# sourceMappingURL=index.js.map
