import{i as l,a as b,S as L}from"./assets/vendor-Dpd1z_xS.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const y of r.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&u(y)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const d=document.querySelector(".gallery"),m=e=>`
  <div class="photo-el">
  <a href="${e.largeImageURL}">
    <img class="mini-image" src="${e.webformatURL}" alt="${e.tags}">
  </a>
  <div class="photo-descr">
  <div class="descr-el"><h2 class="descr-header">Likes</h2><p class="descr-text">${e.likes}</p></div>
  <div class="descr-el"><h2 class="descr-header">Views</h2><p class="descr-text">${e.views}</p></div>
  <div class="descr-el"><h2 class="descr-header">Comments</h2><p class="descr-text">${e.comments}</p></div>
  <div class="descr-el"><h2 class="descr-header">Downloads</h2><p class="descr-text">${e.downloads}</p></div>
  </div>
  </div>`,a=document.querySelector(".loader"),o=document.querySelector(".load-button"),c=document.querySelector(".js-form");let p=1,f,i,h;const g=(e,s)=>b.get(`https://pixabay.com/api/?key=48328522-58f8fcf940ace01c2f71e55b2&q=${s}&image_type=photo&orientation=horizontal&safesearch=true&page=${e}&per_page=15`),w=async()=>{try{p=1;const{data:e}=await g(p,i);if(a.style.display="none",e.totalHits===0){l.show({theme:"dark",icon:"icon-person",message:"Sorry, there are no images matching your search query. Please try again!",position:"center"}),c.reset(),d.innerHTML="",o.style.display="none";return}const s=e.hits.map(n=>m(n)).join("");if(d.innerHTML=s,f=new L(".gallery a",{captions:!0,captionsData:"alt",captionDelay:500}),h=e.hits.length,h<15){o.style.display="none",l.show({theme:"dark",icon:"icon-person",message:"We're sorry, but you've reached the end of search results.",position:"center"});return}o.style.display="block"}catch(e){a.style.display="none",console.log(e)}},S=async e=>{try{if(e.preventDefault(),a.style.display="block",i=c.elements.input.value.trim(),i===""){l.show({theme:"dark",icon:"icon-person",message:"Please enter data to search",position:"center"}),a.style.display="none",c.reset();return}await w(),o.addEventListener("click",v)}catch(s){console.log(s)}},v=async e=>{try{e.preventDefault(),a.style.display="block",o.style.display="none",p++,i=c.elements.input.value.trim();const{data:s}=await g(p,i),n=s.hits.map(r=>m(r)).join("");if(a.style.display="none",d.insertAdjacentHTML("beforeend",n),f.refresh(),h+=s.hits.length,s.hits.length<15||h>=s.totalHits){o.style.display="none",o.removeEventListener("click",v),l.show({theme:"dark",icon:"icon-person",message:"We're sorry, but you've reached the end of search results.",position:"center"});return}o.style.display="block";const t=d.querySelector(".photo-el").getBoundingClientRect().height;window.scrollBy({top:2*t,behavior:"smooth"})}catch(s){a.style.display="none",console.log(s)}};c.addEventListener("submit",S);
//# sourceMappingURL=index.js.map
